### ISSUE TITLE
OpenAPI support

### ISSUE THREAD

**Issue by weiseng18** [modtree/modtree#378]
Want to support routes conforming to OpenAPI specification, so that we can generate docs that can be displayed by Swagger. This can also allow users to test API endpoints. #358 is getting massive (partly due to experimentation) so we'll reapproach this migration with the following steps:

- [x] Sanitize `ModuleFull` data (#376)
- [x] Migrate backend tRPC API from `/` to `/trpc` (#380)
- [x] Add OpenAPI support, mounting the router at `/api` (#382)
- [x] Add descriptions to all routes (#385)
- [x] Replace current API documentation with Swagger (#385)
- [x] Support YAML refs in `trpc-openapi` (#389)
- [x] Test all routes, expecting 200 response (#390)
- [x] Fix docs Swagger base URL (#393)

**Comment by weiseng18** [comment]
done
