### ISSUE TITLE
🔭 Roadmap

### ISSUE THREAD

**Issue by weiseng18** [modtree/modtree#402]
# 🔭 Roadmap

- [ ] Synchronize modules between user, degree, and graphs (#394)
- [ ] Edge entity (create by dragging, split by community/official)
- [ ] Support semesters
- [ ] Module suggestion
- [ ] Improve module search speed
- [ ] Align modules vertically by semester (by dragging)
- [ ] Check if user can graduate on time
- [ ] Handle graph title clash (#372)
- [ ] Style authentication page (#346)
- [ ] Remind user to mark modules as completed, after the semester ends (#7)

**Comment by ianfromdover** [comment]
When I have CS1101S, can it suggest other mods that have CS1101S as the prereq?
