### ISSUE TITLE
Update developer guides

### ISSUE THREAD

**Issue by nguyenvukhang** [modtree/modtree#406]
In preparation for going open source.

- [x] add mac setup instructions (#408)
- [x] create .env.example (minimum `.env` required for devs to start using) (#412)
- [x] cy-reporter should default to `localhost:8081` if env is not present (#412)
- [x] add ability to open Cypress GUI to `yarn cy`. (#413)
- [x] add support for non-fzf users of `cy-reporter` (allow users to pass in a path to a spec file) (#415)
- [x] #419
- [x] add comments to each package.json script (#414)
- [x] add help text to `yarn test` (#410)
- [x] add `core` alias somewhere in `yarn test` help menu (#410)

Wrap-up todos:
- [ ] write a blog post for this + new things after Milestone 3
- [x] update tech stack section (#408)
